{% set name = "alabaster" %}
{% set version = "0.7.16" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75a8b99c28a5dad50dd7f8ccdd447a121ddb3892da9e53d1ca5cca3106d58d65

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - flit-core >=3.7
  run:
    - python

test:
  imports:
    - alabaster
  requires:
    - pip
  commands:
    - python -c "import alabaster; print(alabaster.get_path())"
    - pip check

about:
  home: https://alabaster.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Lightweight, configurable Sphinx theme
  description: |
    Alabaster is a visually (c)lean, responsive, configurable theme for the Sphinx documentation system.
  doc_url: https://alabaster.readthedocs.io/
  dev_url: https://github.com/sphinx-doc/alabaster

extra:
  recipe-maintainers:
    - msarahan
    - r-jain1
    - ocefpaf
